[ubuntu_nodes]
vm-docker       ansible_host=192.168.0.69   vmid=101

[debian_nodes]
lxc-tailscale   ansible_host=192.168.0.155  vmid=1000

[docker_hosts]
vm-docker

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_ed25519

