---
- name: Deploy Docker stacks
  hosts: docker_hosts
  become: true

  vars:
    local_stacks_path: "{{ playbook_dir }}/../../docker/stacks"

  roles:
    - role: sync_docker_stacks
      # TODO: Use a docker stack restart like the one dockge does.
      #       Otherwise stack does not reload config changes.
    - role: deploy_docker_stacks
