---
title: "HomeLab"
subtitle: "Dashboard"

logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/homer.png"
favicon: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/homer.png"
connectivityCheck: true

services:
  - name: "Infrastructure & Server"
    icon: "fas fa-server"
    items:
      - name: "Proxmox"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/proxmox.png"
        subtitle: "Hypervisor"
        url: "https://10.0.10.10:8006"
        target: "_blank"

      - name: "Proxmox Backup Server"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/proxmox.png"
        subtitle: "Backup Server"
        url: "https://10.0.40.20:8007"
        target: "_blank"

      - name: "TrueNAS"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/truenas.png"
        subtitle: "NAS Storage"
        url: "http://10.0.40.100"
        target: "_blank"

      - name: "Dockge"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/dockge.png"
        subtitle: "Docker Container"
        url: "http://10.0.40.40:5001"
        target: "_blank"

      - name: "Synology"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/synology.png"
        subtitle: "Backup Server"
        url: "https://10.0.40.10:5001/"
        target: "_blank"

      - name: "Home Assistant"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/home-assistant.png"
        subtitle: "Smart Home"
        url: "http://10.0.10.198:8123/lovelace/default_view"
        target: "_blank"

      - name: "Home Assistant New"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/home-assistant.png"
        subtitle: "Smart Home"
        url: "http://10.0.40.30:8123/lovelace/default_view"
        target: "_blank"

      - name: "Grafana"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/grafana.png"
        subtitle: "Dashboards"
        url: "http://10.0.40.40:3000"
        target: "_blank"

      - name: "Alloy"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/alloy.png"
        subtitle: "Data Scraping"
        url: "http://10.0.40.40:12345"
        target: "_blank"

  # TODO: Add ansible playbook to update dashboard -> nice to have

  - name: "Files & Media"
    icon: "fas fa-photo-video"
    items:
      - name: "Immich"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/immich.png"
        subtitle: "Photos"
        url: "http://10.0.40.100:2283"
        target: "_blank"

      - name: "Jellyfin"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/jellyfin.png"
        subtitle: "Streaming"
        url: "http://10.0.40.10:8096"
        target: "_blank"

      - name: "Filebrowser"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/filebrowser.png"
        subtitle: "File Manager"
        url: "http://10.0.40.100:8181"
        target: "_blank"

      - name: "RustFS"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/rustfs.png"
        subtitle: "S3 File Server"
        url: "https://10.0.40.100:9000/rustfs/console/auth/login/"
        target: "_blank"

  - name: "Tools & Apps"
    icon: "fas fa-tools"
    items:
      - name: "Paperless-ngx"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/paperless-ngx.png"
        subtitle: "Document Management"
        url: "http://10.0.40.100:8000"
        target: "_blank"

      - name: "qBittorrent"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/qbittorrent.png"
        subtitle: "Downloads"
        url: "http://10.0.40.100:8085"
        target: "_blank"

      - name: "Frigate"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/frigate.png"
        subtitle: "Cameras"
        url: "https://10.0.40.100:5000"
        target: "_blank"

      - name: "BentoPDF"
        logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/master/png/bentopdf.png"
        subtitle: "PDF Tools"
        url: "http://10.0.40.100:8282"
        target: "_blank"
