---
- name: Push local stacks to remote
  ansible.posix.synchronize:
    src: "{{ local_stacks_path }}/"
    dest: "{{ dockge_stacks_path }}/"
    recursive: true
    rsync_opts:
      - "--exclude=data"

- name: Pull remote-only stacks to local git
  ansible.posix.synchronize:
    src: "{{ dockge_stacks_path }}/"
    dest: "{{ local_stacks_path }}/"
    recursive: true
    mode: pull
    rsync_opts:
      - "--exclude=dockge"
