version: "3"

vars:
  PLAYBOOK: "{{.REPO_ROOT}}/ansible/playbooks/docker.yaml"

tasks:
  deploy:
    desc: "Copy docker stacks to the docker VM and deploy"
    silent: true
    deps: [":init"]
    cmd: |
      "{{.VENV}}/bin/ansible-playbook" "{{.PLAYBOOK}}" \
      --vault-password-file "{{.VAULT_PWD_FILE}}"
