version: "3"

tasks:
  deploy:
    desc: "Copy docker stacks to the docker VM and deploy"
    silent: true
    deps: [":init"]
    cmd: |
      "{{.VENV}}/bin/ansible-playbook" "{{.PLAYBOOK}}" \
      --vault-password-file "{{.VAULT_PWD_FILE}}" \
      --extra-vars "docker_state=up"

  restart:
    desc: "Restart a single docker stack on the docker VM"
    silent: true
    deps: [":init"]
    requires:
      vars:
        - name: STACK
          enum: [observability, roastbeef-swag, timescaledb]
    cmd: |
      "{{.VENV}}/bin/ansible-playbook" "{{.PLAYBOOK}}" \
      --vault-password-file "{{.VAULT_PWD_FILE}}" \
      --extra-vars "target_stack={{.STACK}}"
