version: "3"

vars:
  REPO_ROOT:
    sh: git rev-parse --show-toplevel
  VENV: "{{.REPO_ROOT}}/ansible/.venv"
  VAULT_PWD_FILE: "{{.REPO_ROOT}}/ansible/inventory/group_vars/all/.vault.pass"

includes:
  proxmox:
    taskfile: ./taskfiles/proxmox.yaml
    vars:
      VENV: "{{.VENV}}"
      VAULT_PWD_FILE: "{{.VAULT_PWD_FILE}}"
      PLAYBOOK: "{{.REPO_ROOT}}/ansible/playbooks/proxmox.yaml"
  docker:
    taskfile: ./taskfiles/docker.yaml
    vars:
      VENV: "{{.VENV}}"
      VAULT_PWD_FILE: "{{.VAULT_PWD_FILE}}"
      PLAYBOOK: "{{.REPO_ROOT}}/ansible/playbooks/docker.yaml"

tasks:
  init:
    desc: "Install all required dependencies to run the playbooks"
    silent: true
    sources:
      - "{{.REPO_ROOT}}/ansible/requirements.txt"
      - "{{.REPO_ROOT}}/ansible/requirements.yaml"
    generates:
      - "{{.VENV}}/last-updated" # dummy to save last-updated timestamp
    cmds:
      - python3 -m venv "{{.VENV}}"
      - "{{.VENV}}/bin/pip install -r {{.REPO_ROOT}}/ansible/requirements.txt"
      - "{{.VENV}}/bin/ansible-galaxy collection install -r {{.REPO_ROOT}}/ansible/requirements.yaml"
      - touch "{{.VENV}}/last-updated"
