---
- name: Find all valid Docker Compose files on the remote host
  ansible.builtin.find:
    paths: "{{ dockge_stacks_path }}"
    patterns:
      - "docker-compose.yaml"
      - "docker-compose.yml"
      - "compose.yaml"
      - "compose.yml"
    file_type: file
    recurse: yes
  register: compose_files
  when: inventory_hostname in groups['docker_hosts']

- name: "{{ docker_state | capitalize }} Dockge stacks"
  shell: "docker compose {{ 'up -d' if docker_state == 'up' else 'down' }}"
  args:
    chdir: "{{ item.path | dirname }}"
  loop: "{{ compose_files.files }}"
  when:
    - inventory_hostname in groups['docker_hosts']
    - (item.path | dirname | basename) != 'dockge'
  ignore_errors: true
