---
- name: Find all docker stack compose files
  ansible.builtin.find:
    paths: "{{ dockge_stacks_path }}"
    patterns:
      - "docker-compose.yaml"
      - "docker-compose.yml"
      - "compose.yaml"
      - "compose.yml"
    file_type: file
    recurse: true
  register: compose_files

- name: "{{ docker_state | capitalize }} docker stacks"
  vars:
    _compose_args: { up: "up -d", down: "down", restart: "restart" }
  ansible.builtin.shell: "docker compose {{ _compose_args[docker_state] }}"
  args:
    chdir: "{{ item.path | dirname }}"
  loop: "{{ compose_files.files }}"
  when: (item.path | dirname | basename) != 'dockge'
  ignore_errors: true
