---
- name: Ensure rsync is installed
  ansible.builtin.package:
    name: rsync
    state: present
  when: sync_stacks

- name: Push local stacks to remote
  ansible.posix.synchronize:
    src: "{{ local_stacks_path }}/"
    dest: "{{ dockge_stacks_path }}/"
    recursive: true
  when: sync_stacks

- name: Pull remote-only stacks to local git
  ansible.posix.synchronize:
    src: "{{ dockge_stacks_path }}/"
    dest: "{{ local_stacks_path }}/"
    recursive: true
    mode: pull
    rsync_opts:
      - "--exclude=dockge"
  when: sync_stacks

- name: Find all compose files on host
  ansible.builtin.find:
    paths: "{{ dockge_stacks_path }}"
    patterns:
      - "docker-compose.yaml"
      - "docker-compose.yml"
      - "compose.yaml"
      - "compose.yml"
    file_type: file
    recurse: true
  register: compose_files

- name: "{{ docker_state | capitalize }} stacks"
  vars:
    _compose_args: { up: "up -d", down: "down" }
  ansible.builtin.shell: "docker compose {{ _compose_args[docker_state] }}"
  args:
    chdir: "{{ item.path | dirname }}"
  loop: "{{ compose_files.files }}"
  when: (item.path | dirname | basename) != 'dockge'
  ignore_errors: true
